// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvYunnawWGRJkB9xyedihvXadVeApfljc',
    appId: '1:579074026279:web:b68b77480a54d94b991702',
    messagingSenderId: '579074026279',
    projectId: 'collegeproject-1c4a8',
    authDomain: 'collegeproject-1c4a8.firebaseapp.com',
    storageBucket: 'collegeproject-1c4a8.appspot.com',
    measurementId: 'G-CGLPJMKGBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbaXgaiEF69E6rB9LiXs5VlyjfR86bI6Q',
    appId: '1:579074026279:android:0f0414008428b347991702',
    messagingSenderId: '579074026279',
    projectId: 'collegeproject-1c4a8',
    storageBucket: 'collegeproject-1c4a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ADIr2g19XhkUjBhuWH-YqfYV1k_ivxM',
    appId: '1:579074026279:ios:910b372ab1c12db4991702',
    messagingSenderId: '579074026279',
    projectId: 'collegeproject-1c4a8',
    storageBucket: 'collegeproject-1c4a8.appspot.com',
    iosClientId: '579074026279-con5qj292vhagv4pnl7u93n7rsp1rdr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ADIr2g19XhkUjBhuWH-YqfYV1k_ivxM',
    appId: '1:579074026279:ios:910b372ab1c12db4991702',
    messagingSenderId: '579074026279',
    projectId: 'collegeproject-1c4a8',
    storageBucket: 'collegeproject-1c4a8.appspot.com',
    iosClientId: '579074026279-con5qj292vhagv4pnl7u93n7rsp1rdr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication5',
  );
}
